workspace = { members = ["bchain", "client", "learncoin-contracts", "network", "client"]  }
[package]
name = "learn_coin"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal
client = {path = "client"}
bchain = {path = "bchain"}
network = {path = "network"}

# external
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
