[package]
name = "network"
version = "0.1.0"
edition = "2021"

[lib]
name = "network"
path = "src/lib.rs"

[dependencies]
bchain = {path = "../bchain"}
serde = { version = "1.0", features = ["derive"] }
